\encoding UTF8
\c casemng;

DROP TABLE IF EXISTS student_org_links CASCADE;
DROP TABLE IF EXISTS transfer_logs CASCADE;
DROP TABLE IF EXISTS attachments CASCADE;
DROP TABLE IF EXISTS case_histories CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS tree_nodes CASCADE;
DROP TABLE IF EXISTS network_orgs CASCADE;
DROP TABLE IF EXISTS users CASCADE;
